### ISSUE TITLE
cpu6800.c

### ISSUE THREAD

**Issue by ch08kd** [colinbourassa/crasm#2]
It seems that the JSR opcode is turned into $9D when subroutines are in page 0, it is fine otherwise. I changed the JSR to use standard3 rather than standard2 and it seems to work reliably. Can I get a crasm expert to verify my change?  An example is below.

            ORG      0
0000 7E 0004            JMP       PAST
0003 39                   SUB1   RTS
0004 9D FD PAST   JSR      SUB1   <- 9D is an undocumented opcode HCF - Halt and Catch Fire

**Comment by leonbottou** [comment]
Fixed with commit 9c4fcf38316bfe7fc2365fe05432cd1f38aa6128
