### ISSUE TITLE
6502 lda zeropage,x with a label initialized from the program counter makes subsequent labels off by one

### ISSUE THREAD

**Issue by johnnyfs** [colinbourassa/crasm#4]
Hey, I really enjoy your assembler & use it often. I found one bug in an edge case:

Steps to reproduce
* initialize a zero page label from the program counter (in dummy or code) 
* in code, use `lda LABEL, x`

Crasm correctly assembles `B5 LABEL_LOW_BYTE`, but afterward all labels are off by one w/r/t the listing, *as if* `BD LABEL_WORD` had been assembled instead. Specifically, the listing is correct, but the values used by the labels in code are `listing + 1`.

Example
```
        cpu     6502
        list    on

*=0
zp_var=*

*=8000
        code
main    lda     label3
label1  lda     label2
        lda     zp_var, x
        nop
label2  lda     label1 
label3  dw      $4345
~                     
```
Produces this listing
```
  0000                   4  *=0
  0000                   5  zp_var=*
                         6  
  1F40                   7  *=8000
                         8          code
1F40 AD4D1F              9  main    lda     label3
1F43 AD4A1F             10  label1  lda     label2
1F46 B500               11          lda     zp_var, x
1F48 EA                 12          nop
1F49 AD431F             13  label2  lda     label1
1F4C 4543               14  label3  dw      $4345
                        15 
```
Note the label `label1` is correctly assembled as `1FF3`, but `label2` and `label3` are `1F49 => 1F4A` and `1F4C => 1F4D`.

This causes undefined behavior when running, although it's not a showstopper, as `db $B5, LABEL & $ff` works as a workaround. (Note that `lda LABEL & $ff, x` is not sufficient, however.)

Also, if it helps
* `lda WORD_LESS_THAN_256, x` does not trigger the bug
* `lda LABEL_INITIALIZED_TO_WORD_LESS_THAN_256_NOT_USING_PC` as does not

**Comment by leonbottou** [comment]
I just pushed two commits into Colin's github that should fix this kind 
of problems.

Note that the optimization of the zero-page addressing modes only 
happens when the expression does not depend on a label that is defined 
later in the code. Without this restriction, the assembler would need to 
perform three or more passes...

- Leon

**Comment by leonbottou** [comment]
```
Crasm 1.10:                                                   page  1

                         1          cpu     6502
                         2          list    on
                         3  
  0000                   4  *=0
  0000                   5  zp_var=*
                         6  
  1F40                   7  *=8000
                         8          code
1F40 AD4C1F              9  main    lda     label3
1F43 AD491F             10  label1  lda     label2
1F46 B500               11          lda     zp_var, x
1F48 EA                 12          nop
1F49 AD431F             13  label2  lda     label1
1F4C 4543               14  label3  dw      $4345
                        15  
                        16  

ERRORS:       0
WARNINGS:     0
```

**Comment by johnnyfs** [comment]
Thanks, I also confirmed locally that the fix works.
